version: "3.3"

services:
  app:
    build: .
    container_name: "FLask_Shipay"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db
    links: 
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql  
    container_name: "MySQL_DB"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "pdv"